# Exclude specific paths or files from linting
excluded:
  - SwiftFluentTests

disabled_rules:
    - line_length
    - file_length
    - type_body_length
    - multiple_closures_with_trailing_closure

function_body_length:
    warning: 100
    error: 150

identifier_name:
    min_length:
    error: 3
    validates_start_with_lowercase: true


reporter: "xcode"
